# Generated by Django 5.1.2 on 2024-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('RIPU', models.CharField(max_length=200)),
                ('UGE', models.CharField(max_length=200)),
                ('CGE', models.CharField(max_length=200)),
                ('VBENFEITORIA', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Valor da Benfeitoria')),
                ('DATA_AVALIA', models.CharField(max_length=200, verbose_name='Data da última avaliação')),
                ('DATA_DEPREC', models.CharField(max_length=200, verbose_name='Dt. Depreciação')),
                ('IDADE', models.PositiveSmallIntegerField()),
                ('FDEPRECACUMU', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Fator Depreciação Calculado (FDC)')),
                ('VDEPRECACUMU', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Valor acumulado de depreciação desde a ultima avaliação(R$)')),
                ('VDEPRECMES', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Valor de depreciação no mês(R$)')),
            ],
        ),
    ]
