# Generated by Django 5.1.2 on 2024-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciacao',
            name='CGE',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='depreciacao',
            name='DATA_DEPREC',
            field=models.CharField(max_length=200, null=True, verbose_name='Dt. Depreciação'),
        ),
        migrations.AlterField(
            model_name='depreciacao',
            name='IDADE',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
