# Generated by Django 5.1.2 on 2024-10-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0002_alter_depreciacao_cge_alter_depreciacao_data_deprec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciacao',
            name='DATA_AVALIA',
            field=models.DateField(blank=True, null=True, verbose_name='data da última avaliação'),
        ),
        migrations.AlterField(
            model_name='depreciacao',
            name='DATA_DEPREC',
            field=models.DateField(blank=True, null=True, verbose_name='data da depreciação'),
        ),
    ]
