# Generated by Django 5.1.2 on 2024-10-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0003_alter_depreciacao_data_avalia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciacao',
            options={'ordering': ['RIPU', 'referencia']},
        ),
        migrations.AlterUniqueTogether(
            name='depreciacao',
            unique_together={('referencia', 'RIPU')},
        ),
        migrations.AddField(
            model_name='depreciacao',
            name='CC',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='CGE',
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='DATA_DEPREC',
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='FDEPRECACUMU',
        ),
        migrations.RemoveField(
            model_name='depreciacao',
            name='IDADE',
        ),
    ]
