# Generated by Django 5.1.2 on 2024-10-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0004_alter_depreciacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciacao',
            options={'ordering': ['RIPU', 'REF']},
        ),
        migrations.RenameField(
            model_name='depreciacao',
            old_name='referencia',
            new_name='REF',
        ),
        migrations.AlterUniqueTogether(
            name='depreciacao',
            unique_together={('REF', 'RIPU')},
        ),
    ]
