# Generated by Django 5.1.2 on 2024-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0005_alter_depreciacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciacao',
            name='VBENFEITORIA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da Benfeitoria'),
        ),
        migrations.AlterField(
            model_name='depreciacao',
            name='VDEPRECACUMU',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor acumulado de depreciação desde a ultima avaliação(R$)'),
        ),
        migrations.AlterField(
            model_name='depreciacao',
            name='VDEPRECMES',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor de depreciação no mês(R$)'),
        ),
    ]
