# Generated by Django 5.1.2 on 2024-10-25 03:14

from django.db import migrations, models
from DImUniao.models import Depreciacao


class Migration(migrations.Migration):

    dependencies = [
        ('DImUniao', '0006_alter_depreciacao_vbenfeitoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciacao',
            name='MES',
            field=models.DateField(blank=True, null=True, verbose_name='mês'),
        ),
    ]

# for objeto in Depreciacao.objects.all():
#     objeto.MES = objeto.REF[3:7]+"-"+objeto.REF[0:2]+"-"+"01"
#     objeto.save()
